// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasswordGeneratorApp.Models;

namespace PasswordGeneratorApp.Migrations
{
    [DbContext(typeof(PasswordContext))]
    [Migration("20210803142557_AddPasswordField")]
    partial class AddPasswordField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PasswordGeneratorApp.Models.Password", b =>
                {
                    b.Property<long>("PasswordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("SitePassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PasswordId");

                    b.HasIndex("PersonId");

                    b.ToTable("Passwords");

                    b.HasData(
                        new
                        {
                            PasswordId = 1L,
                            CreateDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpireDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonId = 1L,
                            SitePassword = "t3stPassword!",
                            SiteURL = "www.gmail.com"
                        });
                });

            modelBuilder.Entity("PasswordGeneratorApp.Models.Person", b =>
                {
                    b.Property<long>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1L,
                            FirstName = "Tyler",
                            LastName = "Hochstetler"
                        });
                });

            modelBuilder.Entity("PasswordGeneratorApp.Models.Password", b =>
                {
                    b.HasOne("PasswordGeneratorApp.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
